# Owner
OWNER = GameModeler

# The version name (Will be displayed in the root folder and tgz file name).
VERSION = 0.1.0

# Documentation location
DOCUMENTATION_URL = http://your-site.com/$(VERSION)
TOS_URL = http://your-site.com/
ICON_URL = http://your-site.com/icon.png

# Url, branch, etc.
SITE_NAME = your-site.com
SITE_REPO = /var/www/your-site.com.com/path-to-store
OSVERSION = WindowsWPF

# Common folder
COMMON_FOLDER = ../
RELEASE_FOLDER = release-win
NUGET_FOLDER = release-win-nuget

# Reach sources
PLATFORM = win
PLATFORM_UPPERCASE = `echo $(PLATFORM) | tr a-z A-Z`
PACKAGE_BASE = gamemodeler-packaging

# Path to the demo lib folder
DEMO_LIB_FOLDER = $(COMMON_FOLDER)/sln/packages/GameModeler.Windows.$(VERSION)/lib/$(PLATFORM)/

# Nuget package name
PACKAGENUGETNAME = $(OWNER).$(OSVERSION)
PACKAGENUGETEXTENSION = .nupkg
PACKAGENUGETFULLNAME = $(PACKAGENUGETNAME).$(VERSION)$(PACKAGENUGETEXTENSION)